# Generated by Django 4.1.5 on 2024-12-10 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsApp', '0004_delete_faculty'),
        ('StudentApp', '0002_students_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DetailsApp.department'),
        ),
        migrations.AlterField(
            model_name='students',
            name='Sem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DetailsApp.semester'),
        ),
    ]
