# Generated by Django 4.1.5 on 2024-12-11 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsApp', '0019_alter_studentdatabase_created_at'),
        ('StudentApp', '0003_students_department_alter_students_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DetailsApp.class'),
        ),
    ]
