# Generated by Django 4.1.5 on 2024-12-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsApp', '0004_delete_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=255)),
                ('CLASS', models.CharField(max_length=255)),
                ('SUB', models.CharField(max_length=255)),
                ('SEM', models.CharField(max_length=255)),
                ('USN', models.CharField(max_length=255)),
                ('ATT', models.CharField(max_length=255)),
            ],
        ),
    ]
