# Generated by Django 4.1.5 on 2024-12-10 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsApp', '0005_class_studentdatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
