# Generated by Django 4.1.5 on 2024-12-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsApp', '0006_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdatabase',
            name='NAME',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
