# Generated by Django 4.1.5 on 2024-12-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsApp', '0009_alter_studentdatabase_att'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdatabase',
            name='ATT',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
