# Generated by Django 4.1.5 on 2024-12-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsApp', '0010_alter_studentdatabase_att'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdatabase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
