# Generated by Django 4.1.5 on 2024-12-11 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsApp', '0011_studentdatabase_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdatabase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
