# Generated by Django 4.1.5 on 2024-12-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsApp', '0012_alter_studentdatabase_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdatabase',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
