# Generated by Django 4.1.5 on 2024-12-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsApp', '0013_alter_studentdatabase_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdatabase',
            name='created',
        ),
    ]
