# Generated by Django 4.1.5 on 2024-12-11 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsApp', '0014_remove_studentdatabase_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdatabase',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
