# Generated by Django 4.1.5 on 2024-12-11 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsApp', '0015_studentdatabase_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdatabase',
            name='date',
        ),
        migrations.AddField(
            model_name='studentdatabase',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 12, 11, 15, 45, 56, 97096, tzinfo=datetime.timezone.utc)),
        ),
    ]
