# Generated by Django 4.1.5 on 2024-12-11 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsApp', '0016_remove_studentdatabase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdatabase',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 12, 11, 16, 2, 58, 829922, tzinfo=datetime.timezone.utc)),
        ),
    ]
