# Generated by Django 4.1.5 on 2024-12-11 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsApp', '0017_alter_studentdatabase_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdatabase',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 12, 11, 16, 7, 6, 859990, tzinfo=datetime.timezone.utc)),
        ),
    ]
